name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Tjekker koden ud fra repo'et
      - name: Check out code
        uses: actions/checkout@v3

      # Opsætning af Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Installerer afhængigheder
      - name: Install dependencies
        run: npm install

      # Kører tests
      - name: Run tests
        run: npm test

      # Bygger applikationen
      - name: Build application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      # Tjekker koden ud igen for deployment
      - name: Check out code
        uses: actions/checkout@v3

      # Opsætning af Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Installerer afhængigheder igen
      - name: Install dependencies
        run: npm install --production

      # Bygger applikationen
      - name: Build application
        run: npm run build

      # Udfører deployment (fx til en server via FTP eller S3)
      - name: Deploy to server
        run: |
          echo "Deploying..."
          # Tilføj din deployment script her, fx via scp eller en API

